[package]
name = "stdlib"
version = "0.1.0"
authors = ["Levi Harrison <levisamuelharrison@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
func = { path = "../func" }
