[package]
name = "core"
version = "0.1.0"
authors = ["Levi Harrison <git@leviharrison.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
html5ever = "0.25.1"
