[package]
name = "loader"
version = "0.1.0"
authors = ["Levi Harrison <git@leviharrison.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stdlib = { path = "../stdlib" }
core = { path = "../core" }
